export interface DemandaInterface {
    id?: number,
    nombre_demanda?: string,
    tipo_demanda?: string,
    programa_presupuestal?: string,
    actv_presupuestal?: string,
    concepto_demanda?: string,
    prioridad_demanda?: string,
    criterio_demanda?: string,
    id_prioridad?: number,
    objetivo_demanda?: string,
    nombre_ugp?:string,
    criterios?: string,
    foca_1?: string,
    foca_2?: string,
    foca_3?: string,
    justificacion_1?: string,
    justificacion_2?: string,
    justificacion_3?: string,
    observacion_1?: string,
    observacion_2?: string,
    observacion_3?: string,
    brecha?: string,
    indicador?: string,
    unidad_medidad?: string,
    es_pesimista?: number,
    es_conservador?: number,
    es_optimo?: number,
    presupuesto_1?: number,
    presupuesto_2?: number,
    presupuesto_3?: number,
    id_clasificadores?: number,
    usuario_registro?: string
    observacion?: string
    situacion?: number,
    prioridad?: number,
    id_ugp?: number,
    id_epp ?: number,
    id_eap ?: number,
}
